/-
Copyright (c) 2026 Mathlib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mathlib contributors
-/
module

public import Mathlib.Combinatorics.SimpleGraph.Dart
public import Mathlib.Combinatorics.SimpleGraph.DegreeSum
public import Mathlib.Combinatorics.SimpleGraph.Finite
public import Mathlib.Combinatorics.SimpleGraph.Walk.Basic
public import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected

public import Mathlib.Combinatorics.SimpleGraph.PlaneMap.Construction
public import Mathlib.Combinatorics.SimpleGraph.CycleGraph

/-!
# Combinatorial plane maps

Plane maps are connected rotation systems generated from one vertex by attaching
leaves at corners and inserting missing edges within a face. Euler's formula is
proved from the face-orbit correspondences for these operations. Face-length
counting gives the edge bound, a vertex of degree at most five, and the edge
count for triangulations. `PlaneMap.Examples` builds every cycle of length at
least 3 and the tetrahedron `⊤` on `Fin 4`. `PlaneMap.Jordan` begins the
even-set analysis used for combinatorial Jordan. No colouring theorem is
included.
-/

@[expose] public section

namespace SimpleGraph

open scoped BigOperators

universe u

variable {V : Type u} {G : SimpleGraph V}

/-- The graph, rotation, and connectedness carried by a combinatorial map. -/
structure PlaneMapData (n : ℕ) where
  /-- The underlying finite simple graph. -/
  graph : SimpleGraph (Fin n)
  /-- The cyclic order of outgoing darts at every vertex. -/
  rotation : RotationSystem graph
  /-- The underlying graph is connected. -/
  connected : graph.Connected

namespace PlaneMapData

/-- The connected one-vertex map, with no darts. -/
def vertex : PlaneMapData 1 where
  graph := ⊥
  rotation := {
    next := Equiv.refl _
    next_fst := fun _ => rfl
    cyclic := fun d => False.elim d.adj }
  connected := ⟨preconnected_bot⟩

/-- Attach the new last vertex at a corner. -/
noncomputable def grow {n : ℕ} (M : PlaneMapData n) (u : Fin n)
    (c : M.rotation.Corner u) : PlaneMapData (n + 1) where
  graph := PlaneMapConstruction.growGraph M.graph u
  rotation := PlaneMapConstruction.grow u M.rotation M.connected c
  connected := PlaneMapConstruction.grow_graph_connected u M.connected

/-- Insert an edge with its two ends at the specified outgoing darts. -/
noncomputable def split {n : ℕ} (M : PlaneMapData n) (a b : M.graph.Dart)
    (hfst : a.fst ≠ b.fst) (hadj : ¬ M.graph.Adj a.fst b.fst) : PlaneMapData n where
  graph := PlaneMapConstruction.splitGraph M.graph a.fst b.fst hfst
  rotation := PlaneMapConstruction.split M.rotation a b hfst hadj
  connected := PlaneMapConstruction.split_graph_connected a.fst b.fst hfst M.connected

/-- Generation by a vertex, attachment at a corner, and insertion within a face. -/
inductive Generated : {n : ℕ} → PlaneMapData n → Prop
  | vertex : Generated vertex
  | grow {n : ℕ} {M : PlaneMapData n} (hM : Generated M) (u : Fin n)
      (c : M.rotation.Corner u) : Generated (M.grow u c)
  | split {n : ℕ} {M : PlaneMapData n} (hM : Generated M) (a b : M.graph.Dart)
      (hface : M.rotation.faceOf a = M.rotation.faceOf b)
      (hfst : a.fst ≠ b.fst) (hadj : ¬ M.graph.Adj a.fst b.fst) :
      Generated (M.split a b hfst hadj)

end PlaneMapData

/-- A connected rotation system generated by attachment and same-face edge insertion. -/
inductive PlaneMap : ℕ → Type
  | mk {n : ℕ} (data : PlaneMapData n) (generated : data.Generated) : PlaneMap n

namespace PlaneMap

variable {n : ℕ}

/-- The connected rotation-system data of a generated plane map. -/
abbrev data (M : PlaneMap n) : PlaneMapData n := match M with | .mk d _ => d

theorem generated (M : PlaneMap n) : M.data.Generated := by
  cases M with | mk d h => exact h

/-- The underlying simple graph. -/
abbrev graph (M : PlaneMap n) : SimpleGraph (Fin n) := M.data.graph

/-- The vertex rotation system. -/
abbrev rotation (M : PlaneMap n) : RotationSystem M.graph := M.data.rotation

theorem connected (M : PlaneMap n) : M.graph.Connected := M.data.connected

/-- Adjacency in the underlying graph. -/
abbrev Adj (M : PlaneMap n) : Fin n → Fin n → Prop := M.graph.Adj

/-- The oriented edges of a plane map. -/
abbrev Dart (M : PlaneMap n) := M.graph.Dart

/-- The faces of a plane map, including the empty face of the one-vertex map. -/
abbrev Face (M : PlaneMap n) := M.rotation.Face

/-- The face containing a given dart. -/
abbrev faceOf (M : PlaneMap n) (a : M.Dart) : M.Face := M.rotation.faceOf a

noncomputable instance (M : PlaneMap n) : DecidableRel M.graph.Adj := Classical.decRel _

/-- The number of vertices. -/
def v (_M : PlaneMap n) : ℕ := Fintype.card (Fin n)

/-- The number of edges. -/
noncomputable def e (M : PlaneMap n) : ℕ := M.graph.edgeFinset.card

/-- The number of faces. -/
noncomputable def f (M : PlaneMap n) : ℕ := M.rotation.faceCount

/-- The number of darts on a face boundary. -/
noncomputable def faceLength (M : PlaneMap n) (q : M.Face) : ℕ := M.rotation.faceLength q

/-- Start the construction with one vertex and its empty face. -/
def vertex : PlaneMap 1 := .mk PlaneMapData.vertex .vertex

/-- Attach the new last vertex at the selected corner. -/
noncomputable def grow (M : PlaneMap n) (u : Fin n) (c : M.rotation.Corner u) :
    PlaneMap (n + 1) := .mk (M.data.grow u c) (.grow M.generated u c)

/-- Insert a missing edge between two different vertices on one face. -/
noncomputable def split (M : PlaneMap n) (a b : M.Dart)
    (hface : M.faceOf a = M.faceOf b) (hfst : a.fst ≠ b.fst) (hadj : ¬ M.Adj a.fst b.fst) :
    PlaneMap n := .mk (M.data.split a b hfst hadj) (.split M.generated a b hface hfst hadj)

@[simp]
theorem vertex_graph : vertex.graph = ⊥ := rfl

@[simp]
theorem vertex_edge_count : vertex.e = 0 := by
  let : IsEmpty vertex.Dart := ⟨fun d => d.adj⟩
  have h := card_dart_eq_twice_card_edges (G := vertex.graph)
  have hd : Fintype.card vertex.Dart = 0 := Fintype.card_eq_zero
  change Fintype.card vertex.Dart = 2 * vertex.e at h
  omega

@[simp]
theorem vertex_face_count : vertex.f = 1 := by
  let : IsEmpty vertex.Dart := ⟨fun d => d.adj⟩
  exact vertex.rotation.face_count_of_is_empty

@[simp]
theorem vertex_face_length (q : vertex.Face) : vertex.faceLength q = 0 := by
  let : IsEmpty vertex.Dart := ⟨fun d => d.adj⟩
  exact vertex.rotation.face_length_of_is_empty q

@[simp]
theorem vertex_count (M : PlaneMap n) : M.v = n := Fintype.card_fin n

@[simp]
theorem grow_vertex_count (M : PlaneMap n) (u : Fin n) (c : M.rotation.Corner u) :
    (M.grow u c).v = M.v + 1 := by simp

@[simp]
theorem grow_edge_count (M : PlaneMap n) (u : Fin n) (c : M.rotation.Corner u) :
    (M.grow u c).e = M.e + 1 := by
  classical
  exact PlaneMapConstruction.grow_card_edges u

@[simp]
theorem grow_face_count (M : PlaneMap n) (u : Fin n) (c : M.rotation.Corner u) :
    (M.grow u c).f = M.f := by
  classical
  exact PlaneMapConstruction.grow_face_count u M.rotation M.connected c

@[simp]
theorem split_edge_count (M : PlaneMap n) (a b : M.Dart)
    (hface : M.faceOf a = M.faceOf b) (hfst : a.fst ≠ b.fst) (hadj : ¬ M.Adj a.fst b.fst) :
    (M.split a b hface hfst hadj).e = M.e + 1 := by
  classical
  exact PlaneMapConstruction.split_card_edges a.fst b.fst hfst hadj

end PlaneMap

namespace PlaneMap

@[simp]
theorem split_face_count {n : ℕ} (M : PlaneMap n) (a b : M.Dart)
    (hface : M.faceOf a = M.faceOf b) (hfst : a.fst ≠ b.fst) (hadj : ¬ M.Adj a.fst b.fst) :
    (M.split a b hface hfst hadj).f = M.f + 1 := by
  classical
  exact PlaneMapConstruction.split_face_count M.rotation a b hfst hadj hface

end PlaneMap

/-- Euler's additive formula for maps generated on the sphere. -/
theorem euler_sphere {n : ℕ} (M : PlaneMap n) : M.v + M.f = M.e + 2 := by
  rcases M with ⟨D, h⟩
  induction h with
  | vertex =>
    change PlaneMap.vertex.v + PlaneMap.vertex.f = PlaneMap.vertex.e + 2
    simp
  | @grow n D h u c ih =>
    change ((PlaneMap.mk D h).grow u c).v + ((PlaneMap.mk D h).grow u c).f =
      ((PlaneMap.mk D h).grow u c).e + 2
    rw [PlaneMap.grow_vertex_count, PlaneMap.grow_face_count, PlaneMap.grow_edge_count]
    omega
  | @split n D h a b hface hfst hadj ih =>
    change ((PlaneMap.mk D h).split a b hface hfst hadj).v +
      ((PlaneMap.mk D h).split a b hface hfst hadj).f =
      ((PlaneMap.mk D h).split a b hface hfst hadj).e + 2
    rw [PlaneMap.vertex_count, PlaneMap.split_face_count, PlaneMap.split_edge_count]
    rw [PlaneMap.vertex_count] at ih
    omega

/-- A spherical map with no face shorter than three has at most `3 * n - 6` edges. -/
theorem edge_bound {n : ℕ} (M : PlaneMap n) (hn : 3 ≤ n)
    (hfaces : ∀ f : M.Face, 3 ≤ M.faceLength f) : M.e ≤ 3 * n - 6 := by
  classical
  have hsum := M.rotation.sum_face_lengths_eq_twice_card_edges
  have hle := Finset.sum_le_sum (s := Finset.univ) (fun f _ => hfaces f)
  have hcount : 3 * M.f ≤ 2 * M.e := by
    simpa [PlaneMap.faceLength, PlaneMap.f, PlaneMap.e, RotationSystem.faceCount,
      Nat.mul_comm] using hle.trans_eq hsum
  have heuler := euler_sphere M
  rw [PlaneMap.vertex_count] at heuler
  have heulerZ : (n : ℤ) + (M.f : ℤ) = (M.e : ℤ) + 2 := by omega
  have hcountZ : 3 * (M.f : ℤ) ≤ 2 * (M.e : ℤ) := by omega
  have hboundZ : (M.e : ℤ) ≤ 3 * (n : ℤ) - 6 := by omega
  omega

/-- Such a map has a vertex of degree at most five. -/
theorem exists_degree_le_five {n : ℕ} (M : PlaneMap n) (hn : 3 ≤ n)
    (hfaces : ∀ f : M.Face, 3 ≤ M.faceLength f) : ∃ v, M.graph.degree v ≤ 5 := by
  classical
  by_contra! hdeg
  have hs : (∑ _v : Fin n, 6) ≤ ∑ v : Fin n, M.graph.degree v :=
    Finset.sum_le_sum (fun v _ => hdeg v)
  have he := M.graph.sum_degrees_eq_twice_card_edges
  have hb := edge_bound M hn hfaces
  change (∑ v : Fin n, M.graph.degree v) = 2 * M.e at he
  simp only [Finset.sum_const, Finset.card_univ, Fintype.card_fin, smul_eq_mul] at hs
  omega

/-- In a triangulation, counting darts gives both the incidence identity and the edge count. -/
theorem triangulation_edge_count {n : ℕ} (M : PlaneMap n)
    (hfaces : ∀ f : M.Face, M.faceLength f = 3) :
    2 * M.e = 3 * M.f ∧ M.e = 3 * n - 6 := by
  classical
  have hsum := M.rotation.sum_face_lengths_eq_twice_card_edges
  change (∑ f : M.Face, M.faceLength f) = 2 * M.e at hsum
  have hcount : 2 * M.e = 3 * M.f := by
    simpa [hfaces, PlaneMap.f, RotationSystem.faceCount, Nat.mul_comm] using hsum.symm
  have heuler := euler_sphere M
  rw [PlaneMap.vertex_count] at heuler
  have heulerZ : (n : ℤ) + (M.f : ℤ) = (M.e : ℤ) + 2 := by omega
  have hcountZ : 2 * (M.e : ℤ) = 3 * (M.f : ℤ) := by omega
  have hedgeZ : (M.e : ℤ) = 3 * (n : ℤ) - 6 := by omega
  exact ⟨hcount, by omega⟩

/-- In a triangulation, the neighbour rotation enumerates a simple cycle through all neighbours. -/
theorem neighbour_rotation {n : ℕ} (M : PlaneMap n) (v : Fin n)
    (hfaces : ∀ f : M.Face, M.faceLength f = 3) (hdegree : 3 ≤ M.graph.degree v) :
    ∃ (k : ℕ) (c : Fin (k + 3) ≃ M.graph.neighborSet v),
      k + 3 = M.graph.degree v ∧
      (∀ i, M.rotation.neighborRotation v (c i) = c (i + 1)) ∧
      (∀ i, M.Adj (c i).val (c (i + 1)).val) ∧
      ∃ p : M.graph.Walk (c 0).val (c 0).val,
        p.IsCycle ∧ p.length = M.graph.degree v ∧
        ∀ z, z ∈ p.support ↔ M.Adj v z := by
  classical
  have hn : Nonempty (M.graph.neighborSet v) := by
    apply Fintype.card_pos_iff.1
    rw [card_neighborSet_eq_degree]
    omega
  obtain ⟨w⟩ := hn
  let σ := M.rotation.neighborRotation v
  let P := Function.minimalPeriod (⇑σ) w
  have hP : P = M.graph.degree v := M.rotation.neighbor_period_eq_degree v w
  obtain ⟨k, hk⟩ : ∃ k, P = k + 3 := ⟨P - 3, by omega⟩
  let c : Fin (k + 3) ≃ M.graph.neighborSet v :=
    (finCongr hk.symm).trans (M.rotation.neighborOrbitEquiv v w)
  have hc (i : Fin (k + 3)) : c i = (⇑σ)^[i.val] w := rfl
  have hnext (i : Fin (k + 3)) : σ (c i) = c (i + 1) := by
    rw [hc, hc]
    have hm : (i.val + 1) % (k + 3) = (i.val + 1) % P := by rw [hk]
    simp only [Fin.val_add, Fin.val_one]
    rw [hm]
    exact (Function.iterate_mod_minimalPeriod_eq.trans
      (Function.iterate_succ_apply' _ _ _)).symm
  have hadj (i : Fin (k + 3)) : M.Adj (c i).val (c (i + 1)).val := by
    rw [← hnext]
    exact M.rotation.neighbor_rotation_adj hfaces v (c i)
  let F : cycleGraph (k + 3) →g M.graph := {
    toFun := fun i => (c i).val
    map_rel' := by
      intro i j h
      rw [cycleGraph_adj] at h
      rcases h with h | h
      · rw [sub_eq_iff_eq_add'] at h
        subst i
        exact (hadj j).symm
      · rw [sub_eq_iff_eq_add'] at h
        subst j
        exact hadj i }
  have hinj : Function.Injective F := fun i j h => c.injective (Subtype.ext h)
  have hmem (i : Fin (k + 3)) : i ∈ (cycleGraph.cycle k).support := by
    have h := (cycleGraph.cycle k).getVert_mem_support (k + 3 - i.val)
    rw [cycleGraph.getVert_cycle (by omega)] at h
    have hi : (⟨(k + 3 - (k + 3 - i.val)) % (k + 3), Nat.mod_lt _ (by omega)⟩ :
        Fin (k + 3)) = i := by
      apply Fin.ext
      have hle := i.isLt
      simp only [Nat.sub_sub_self (by omega : i.val ≤ k + 3), Nat.mod_eq_of_lt hle]
    simpa only [hi] using h
  refine ⟨k, c, hk.symm.trans hP, hnext, hadj, (cycleGraph.cycle k).map F,
    cycleGraph.isCycle_cycle.map hinj, ?_, ?_⟩
  · simpa only [Walk.length_map, cycleGraph.length_cycle] using hk.symm.trans hP
  · intro z
    rw [Walk.support_map, List.mem_map]
    constructor
    · rintro ⟨i, _, rfl⟩
      exact (c i).property
    · intro hz
      obtain ⟨i, hi⟩ := c.surjective ⟨z, hz⟩
      exact ⟨i, hmem i, congrArg Subtype.val hi⟩

end SimpleGraph
